node {
  stage('SCM') {
    git '${GIT_URL}'
  }
  stage('SonarQube analysis') {
    def scannerHome = tool 'sonar-scanner';
    withSonarQubeEnv('sonar-server') {
      sh "${scannerHome}/bin/sonar-scanner"
    }
  }
}