node {
  stage('SCM') {
    git '${GIT_URL}'
  }
  stage('SonarQube analysis') {
    def scannerHome = tool 'SonarQube Scanner 2.8';
    withSonarQubeEnv('sonar-server') {
      sh "${scannerHome}/bin/sonar-scanner"
    }
  }
}